#!/bin/bash

# this script is meant to run very basic and sketchy test cases

# test wrong filter, check the log and stdout
php -f ../php/controller.php delegator=directory action=get filter=or\(sensor\)
