#!/bin/bash

# the sanitized space name
space=$(basename $0)

# the cron jobs will be called from somewhere
# so we need to find out in what directory the
# cron job is located and change into it
cd $(dirname $(readlink -f $0))

# now update the cached json file for $space
cd ../../c/php
/usr/bin/env php -f update-cache.php "$space"
