#!/bin/bash

# This script creates all the (s)cron directories, the space crons themselves
# and populates the cache while updating the schedules according what the spaces
# have defined in their json. This script can also be run to update the cache
# all at once.

if [ $# -ne 1 ];
then
    echo "Please tell me the web server user"
    exit 1;
fi    

# - create the daily tasks directory
# - create the cache reports directory
su $1 -c 'mkdir -p ../cron/daily-tasks'

# create the cache directories
su $1 -c 'mkdir -p ../cache/{status,filter-keys,reports}'
su $1 -c 'echo "*.json" > ../cache/.gitignore'

# create the log directory for the php logger
su $1 -c 'mkdir -p ../log'

# create the space cron directories and the space cronjobs
echo "Creating the cron directories"
su $1 -c '/usr/bin/env php -f create_crondirs.php'
echo "Creating the cron jobs"
su $1 -c '/usr/bin/env php -f create_cronjobs.php'

# now run the daily cronjobs once to populate the cache
echo "Do you want to populate the whole cache? Please press the key 1 or 2."

OPTIONS="yes no" 
select opt in $OPTIONS; do
    case $opt in
        yes)
            echo "Now creating/updating the cache. This can take some minutes."
            su $1 -c 'run-parts ../cron/scron.d.01'           
            break;
            ;;
        no)
            echo "Skipping it ..."
            break
            ;;
        *)
            echo "Bad option" 
    esac
done