#!/bin/bash

# This script creates all the (s)cron directories, the space crons themselves
# and populates the cache while updating the schedules according what the spaces
# have defined in their json. This script can also be run to update the cache
# all at once.

if [ $# -ne 1 ];
then
    echo "Please tell me the web server user"
    exit 1;
fi    

# create the space cron directories
su $1 -c 'mkdir -p ../cron/scron.{m.{02,05,10,15,30},h.{01,02,04,08,12},d.01}'

# create the daily tasks directory
su $1 -c 'mkdir -p ../cron/daily-tasks'

# create the reports directory, where a report file is created or updated after a cache update
su $1 -c 'mkdir -p ../cron/reports'

# create the actual cronjobs
su $1 -c '/usr/bin/env php -f create_cronjobs.php'

echo "Now creating/updating the cache. This can take some minutes."

# now run the daily cronjobs once to populate the cache
su $1 -c 'run-parts ../cron/scron.d.01'
